name: Ping Backend Daily

on:
  schedule:
    - cron: '30 18 * * *'  # This triggers the action daily at 6:30 PM UTC, which is 12:00 AM IST

jobs:
  ping-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP request to backend
        run: |
          curl -X GET https://contestinfo-m59t.onrender.com/data
