name: Ping Backend Daily

on:
  schedule:
    # Schedule Batch 22 Part 1 Data Scrape at 12:00 AM IST
    - cron: '30 18 * * *'  # 6:30 PM UTC
    # Schedule Batch 22 Part 2 Data Scrape at 12:30 AM IST
    - cron: '00 19 * * *'  # 7:00 PM UTC
    # Schedule Batch 22 Part 3 Data Scrape at 1:00 AM IST
    - cron: '30 19 * * *'  # 7:30 PM UTC
    # Schedule Batch 22 Part 4 Data Scrape at 1:30 AM IST
    - cron: '00 20 * * *'  # 8:00 PM UTC

    # Schedule Batch 21 Part 1 Data Scrape at 2:00 AM IST
    - cron: '30 20 * * *'  # 8:30 PM UTC
    # Schedule Batch 21 Part 2 Data Scrape at 2:30 AM IST
    - cron: '00 21 * * *'  # 9:00 PM UTC
    # Schedule Batch 21 Part 3 Data Scrape at 3:00 AM IST
    - cron: '30 21 * * *'  # 9:30 PM UTC
    # Schedule Batch 21 Part 4 Data Scrape at 3:30 AM IST
    - cron: '00 22 * * *'  # 10:00 PM UTC


jobs:
  ping-batch-22-01:
    if: github.event.schedule == '30 18 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Scrape Batch22 Data
        run: |
          curl -X GET https://contestinfo-m59t.onrender.com/22batch/01

      - name: Get Latest Contest Data
        run: |
          curl -X GET https://contestinfo-m59t.onrender.com/getUpcomingContests

  ping-batch-22-02:
    if: github.event.schedule == '00 19 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Scrape Batch22 Data
        run: |
          curl -X GET https://contestinfo-m59t.onrender.com/22batch/02

  ping-batch-22-03:
    if: github.event.schedule == '30 19 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Scrape Batch22 Data
        run: |
          curl -X GET https://contestinfo-m59t.onrender.com/22batch/03
  
  ping-batch-22-04:
    if: github.event.schedule == '00 20 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Scrape Batch22 Data
        run: |
          curl -X GET https://contestinfo-m59t.onrender.com/22batch/04



  ping-batch-21-01:
    if: github.event.schedule == '30 20 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Scrape Batch21 Data
        run: |
          curl -X GET https://contestinfo-m59t.onrender.com/21batch/01

  ping-batch-21-02:
    if: github.event.schedule == '00 21 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Scrape Batch21 Data
        run: |
          curl -X GET https://contestinfo-m59t.onrender.com/21batch/02

  ping-batch-21-03:
    if: github.event.schedule == '30 21 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Scrape Batch21 Data
        run: |
          curl -X GET https://contestinfo-m59t.onrender.com/21batch/03

  ping-batch-21-04:
    if: github.event.schedule == '00 22 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Scrape Batch21 Data
        run: |
          curl -X GET https://contestinfo-m59t.onrender.com/21batch/04